services:
  - type: web
    name: Analytica-web
    env: ruby
    plan: free
    numInstances: 1
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/deploy/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Analytica-web
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: Analytica-web
    plan: free
    postgresMajorVersion: 14