default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: Analytica_development

test:
  <<: *default
  database: Analytica_test

production:
  <<: *default
  database: Analytica_production
  username: Analytica
  url: <%= ENV['DATABASE_URL'] %>
