# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Pull Request workflow

on:
  pull_request:
    branches:
      - main

jobs:
  rubocop: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop -c .rubocop.yml -f progress
  rspec:
    needs: [rubocop, changelog_check]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        # tmpfs makes DB faster by using RAM
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    env:
      RAILS_ENV: test
      GEMFILE_RUBY_VERSION: 3.1.0
      PGHOST: localhost
      PGUSER: postgres
      BASE_URL: 'localhost'

      DELIVERY_SUPPORT_EMAIL: 'test@example.com'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          ruby-version: 3.1.0
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Create DB
        run: |
          bin/rails db:create db:migrate
      - name: Run tests
        run: |
          bundle exec rspec spec
